Mal versuchen, ob man mit Python ein Dashboard bauen kann

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/cleaned_air_quality_data_2025-03-27.csv")
df.head()

,Year,Month,Day,Country,City,Latitude,Longitude,Population,Co,No2,...,So2,Dew,Humidity,Tavg,Tmin,Tmax,Prcp,Wdir,Wspd,Pres
0,2019,2,28,SA,Abha,18.21639,42.50528,5616633.0,NaN,NaN,...,NaN,6.0,45.0,18.8,15.8,24.1,NaN,183.0,21.9,1022.3
1,2019,3,1,SA,Abha,18.21639,42.50528,5616633.0,NaN,NaN,...,NaN,12.0,64.0,17.0,13.5,23.0,NaN,185.0,21.2,1021.9
2,2019,3,2,SA,Abha,18.21639,42.50528,5616633.0,NaN,0.0,...,0.0,9.0,63.0,16.7,10.8,23.6,NaN,186.0,15.2,1022.3
3,2019,3,3,SA,Abha,18.21639,42.50528,5616633.0,NaN,0.0,...,0.0,6.0,55.0,15.9,10.8,22.0,NaN,196.0,16.5,1023.4
4,2019,3,4,SA,Abha,18.21639,42.50528,5616633.0,NaN,0.0,...,0.0,3.0,58.0,16.1,9.0,22.5,NaN,NaN,11.2,1023.8

In [3]:
df["City"].unique()

array(['Abha', 'Abidjan', 'Abu dhabi', 'Accra', 'Adana', 'Adapazarı',
       'Addis ababa', 'Adelaide', 'Aguascalientes', 'Akita',
       'Albuquerque', 'Algiers', 'Almaty', 'Alor setar', 'Amiens',
       'Amman', 'Amsterdam', 'Andong', 'Ankara', 'Antakya', 'Antwerpen',
       'Anyang', 'Arad', 'Arāk', 'Ashdod', 'Ashgabat', 'Ashkelon',
       'Athens', 'Atlanta', 'Auckland', 'Augsburg', 'Austin', 'Bacău',
       'Baghdad', 'Baguio', 'Baia mare', 'Baltimore', 'Balıkesir',
       'Bamako', 'Bandar abbas', 'Bangkok', 'Barcelona', 'Beijing',
       'Belfast', 'Belgrade', 'Bengaluru', 'Bergen', 'Berlin', 'Besançon',
       'Bhopal', 'Bilbao', 'Biratnagar', 'Birmingham', 'Bishkek',
       'Bloemfontein', 'Bogotá', 'Boise', 'Bologna', 'Bordeaux', 'Boston',
       'Bratislava', 'Braşov', 'Breda', 'Brescia', 'Brisbane', 'Bristol',
       'Brno', 'Brooklyn', 'Brussels', 'Brăila', 'Bucharest', 'Budapest',
       'Buenos aires', 'Buraydah', 'Burgas', 'Burgos', 'Bursa', 'Busan',
       'Butuan', 'Bydgoszcz', 'Caen', 'Calama', 'Calgary', 'Canberra',
       'Cape town', 'Cardiff', 'Castelló de la plana', 'Chandigarh',
       'Changchun', 'Changsha', 'Changwon', 'Changzhou', 'Charleroi',
       'Charlotte', 'Chelyabinsk', 'Chengdu', 'Chennai', 'Cheongju-si',
       'Chiang mai', 'Chiba', 'Chicago', 'Chihuahua', 'Chillán',
       'Chon buri', 'Chongqing', 'Christchurch', 'Chuncheon',
       'Clermont-ferrand', 'Cluj-napoca', 'Cochabamba', 'Colombo',
       'Columbia', 'Columbus', 'Conakry', 'Concepción', 'Constanţa',
       'Copenhagen', 'Coventry', 'Craiova', 'Cuernavaca', 'Córdoba',
       'Daegu', 'Daejeon', 'Dallas', 'Dammam', 'Darmstadt', 'Darwin',
       'Debrecen', 'Delhi', 'Denizli', 'Denver', 'Detroit', 'Dhaka',
       'Dijon', 'Dnipro', 'Dongguan', 'Donostia / san sebastián',
       'Dordrecht', 'Douliu', 'Dresden', 'Dubai', 'Dublin', 'Dunedin',
       'Durban', 'Dushanbe', 'Düsseldorf', 'East london',
       'Ecatepec de morelos', 'Edinburgh', 'Edmonton', 'Eindhoven',
       'El paso', 'Erzurum', 'Eskişehir', 'Florence', 'Fort worth',
       'Foshan', 'Freiburg', 'Fresno', 'Fukuoka', 'Funchal', 'Fushun',
       'Fuzhou', 'Galaţi', 'Gandhinagar', 'Gasteiz / vitoria', 'Gdańsk',
       'Gent', 'George town', 'Ghāziābād', 'Gifu-shi', 'Glasgow',
       'Granada', 'Graz', 'Grenoble', 'Groningen', 'Guadalajara',
       'Guangzhou', 'Guatemala city', 'Guiyang', 'Gwangju', 'Győr',
       'Göteborg', "Ha'il", 'Haarlem', 'Haifa', 'Haikou', 'Haiphong',
       'Halifax', 'Hamburg', 'Hamilton', 'Hangzhou', 'Hannover', 'Hanoi',
       'Harbin', 'Hartford', 'Hefei', 'Hegang', 'Helsinki', 'Hiroshima',
       'Ho chi minh city', 'Hobart', 'Hohhot', 'Hong kong', 'Honolulu',
       'Houston', 'Hsinchu', 'Huelva', 'Huế', 'Hyderabad', 'Hāpur',
       'Hạ long', 'Iaşi', 'Incheon', 'Indianapolis', 'Innsbruck', 'Ipoh',
       'Irbid', 'Isfahan', 'Islamabad', 'Istanbul', 'Ivano-frankivsk',
       'İzmir', 'İzmit', 'Jackson', 'Jacksonville', 'Jaipur', 'Jakarta',
       'Jeddah', 'Jeju city', 'Jeonju', 'Jerusalem', 'Jieyang', 'Jinan',
       'Johannesburg', 'Johor bahru', 'Kabul', 'Kagoshima', 'Kamianske',
       'Kampala', 'Kanazawa', 'Kaohsiung', 'Karachi', 'Karaj',
       'Karlsruhe', 'Kassel', 'Kathmandu', 'Katowice', 'Kaunas',
       'Kayseri', 'Kecskemét', 'Keelung', 'Kerman', 'Kermanshah',
       'Khorramabad', 'Khorramshahr', 'Kielce', 'Kitchener', 'Klang',
       'Klerksdorp', 'Kobe', 'Kochi', 'Kolkata', 'Konya', 'Kota bharu',
       'Košice', 'Kraków', 'Krasnoyarsk', 'Kryvyi rih', 'Kuala lumpur',
       'Kuantan', 'Kuching', 'Kumamoto', 'Kunming', 'Kyiv', 'Kyoto',
       'Köln', 'Kütahya', 'Lahore', 'Lampang', 'Lanzhou',
       'Las palmas de gran canaria', 'Las vegas', 'Launceston', 'Leeds',
       'Leicester', 'Lhasa', 'Lille', 'Lima', 'Limassol', 'Limoges',
       'Linz', 'Lisbon', 'Little rock', 'Liverpool', 'Livorno', 'Liège',
       'London', 'Los angeles', 'Los ángeles', 'Lucknow', 'Luton', 'Lviv',
       'Lyon', 'Maastricht', 'Macau', 'Madison', 'Madrid', 'Mainz',
       'Malacca', 'Malmö', 'Manama', 'Manchester', 'Manhattan', 'Manila',
       'Marseille', 'Mashhad', 'Matsuyama', 'Mecca', 'Medellín',
       'Melbourne', 'Memphis', 'Metz', 'Mexico city', 'Miami',
       'Middelburg', 'Milan', 'Milwaukee', 'Miri', 'Miskolc',
       'Mississauga', 'Miyazaki', 'Modena', 'Mokpo', 'Monterrey',
       'Montpellier', 'Montréal', 'Morelia', 'Moscow', 'Mumbai', 'Munich',
       'Murcia', 'Muzaffarnagar', 'Mysore', 'Málaga', 'Mérida', 'Münster',
       'Nagano', 'Nagasaki', 'Nagoya', 'Nagpur', 'Naha', 'Nakhon pathom',
       'Namur', 'Nanchang', 'Nancy', 'Nanjing', 'Nanning', 'Nantes',
       'Naples', 'Nara-shi', 'Nashik', 'Nashville', 'Netanya',
       'New delhi', 'Newcastle', 'Newport', 'Nice', 'Nicosia', 'Niigata',
       'Nijmegen', 'Ningbo', 'Nizhniy novgorod', 'Niš', 'Norwich',
       'Novi sad', 'Novosibirsk', 'Nur-sultan', 'Nîmes', 'Oakland',
       'Oaxaca', 'Odessa', 'Okayama', 'Oklahoma city', 'Olomouc', 'Omaha',
       'Oradea', 'Orléans', 'Orūmīyeh', 'Osaka', 'Oslo', 'Osorno',
       'Ostrava', 'Ottawa', 'Oulu', 'Oviedo', 'Pachuca de soto', 'Palma',
       'Pamplona', 'Paris', 'Parma', 'Patna', 'Perpignan', 'Perth',
       'Peshawar', 'Petaẖ tiqwa', 'Philadelphia', 'Phoenix', 'Pilsen',
       'Piteşti', 'Ploieşti', 'Plovdiv', 'Plymouth', 'Pohang', 'Pokhara',
       'Port elizabeth', 'Portland', 'Potsdam', 'Poznań', 'Prague',
       'Prato', 'Preston', 'Pretoria', 'Pristina', 'Providence', 'Puebla',
       'Puerto montt', 'Pécs', 'Płock', 'Qingdao', 'Qinhuangdao',
       'Qiqihar', 'Qom', 'Queens', 'Quilpué', 'Quito', 'Québec',
       'Raleigh', 'Rancagua', 'Rayong', 'Reading', 'Rennes', 'Reykjavík',
       'Richards bay', 'Richmond', 'Rijeka', 'Riyadh', 'Rome',
       'Rotterdam', 'Rouen', 'Rybnik', 'Râmnicu vâlcea', 'Sacramento',
       'Saint paul', 'Saint petersburg', 'Saint-denis', 'Saint-étienne',
       'Saitama', 'Salamanca', 'Salem', 'Salt lake city', 'Salzburg',
       'Samsun', 'Samut prakan', 'San antonio', 'San diego',
       'San francisco', 'San jose', 'San josé', 'San juan',
       'San luis potosí', 'San salvador', 'Sanandaj',
       'Santa cruz de tenerife', 'Santander', 'Santiago', 'Sapporo',
       'Sarajevo', 'Seattle', 'Sejong', 'Sendai', 'Seongnam-si', 'Seoul',
       'Seremban', 'Sevilla', 'Shanghai', 'Shantou', 'Sheffield',
       'Shenyang', 'Shenzhen', 'Shijiazhuang', 'Shillong', 'Shiraz',
       'Shiyan', 'Shizuoka', 'Sibiu', 'Singapore', 'Sivas', 'Skopje',
       'Sofia', 'Southend-on-sea', 'Split', 'Springfield',
       'Staten island', 'Stavanger', 'Stockholm', 'Strasbourg',
       'Stuttgart', 'Suncheon', 'Surrey', 'Suwon', 'Suzhou', 'Swansea',
       'Sydney', 'Szczecin', 'Szeged', 'São josé dos campos', 'São paulo',
       'Tabriz', 'Taichung', 'Tainan', 'Taipei', 'Taiping',
       'Taitung city', 'Taiyuan', 'Takamatsu', 'Talca', 'Tallahassee',
       'Tallinn', 'Tampere', 'Taoyuan city', 'Tarnów', 'Tashkent',
       'Tbilisi', 'Tehran', 'Tel aviv', 'Temuco', 'Tepic', 'Ternopil',
       'The bronx', 'The hague', 'Thessaloníki', 'Thiruvananthapuram',
       'Thrissur', 'Tianjin', 'Timişoara', 'Tokyo', 'Toluca', 'Tomsk',
       'Toronto', 'Toulon', 'Toulouse', 'Tours', 'Toyama', 'Trabzon',
       'Trieste', 'Trondheim', 'Tucson', 'Turin', 'Turku', 'Tuzla',
       'Ulan bator', 'Ulsan', 'Uppsala', 'Utrecht', 'Utsunomiya',
       'Valencia', 'Valladolid', 'Valparaíso', 'Vancouver', 'Vantaa',
       'Vereeniging', 'Victoria', 'Vienna', 'Vientiane', 'Visakhapatnam',
       'Vitória', 'Wakayama', 'Warsaw', 'Washington d.c.', 'Wellington',
       'Wiesbaden', 'Willemstad', 'Winnipeg', 'Wollongong', 'Worcester',
       'Wrocław', 'Wuhan', 'Wuxi', 'Xiamen', 'Xining', 'Xinxiang',
       'Xi’an', 'Xuchang', 'Yangon', 'Yazd', 'Yeosu', 'Yinchuan',
       'Yokohama', 'Yunfu', 'Zabrze', 'Zagreb', 'Zamboanga', 'Zanjān',
       'Zaporizhia', 'Zaragoza', 'Zarqa', 'Zenica', 'Zhengzhou',
       'Zhuzhou', 'Zürich', 'Ürümqi', 'Īlām', 'Łódź', 'Ōita', 'Ḩawallī'],
      dtype=object)

In [4]:
# Test-DataFrame erstellen
df_small = df[df["City"].isin(["Hamburg", "Berlin", "Karlsruhe"])].copy()

# Spaltenauswahl, z. B.:
columns = ["Year", "Month", "Day", "City", "Pm25", "Co", "No2", "So2", "O3", "Tavg", "Humidity"]
df_small = df_small[columns]

df_small.dropna(inplace=True)

# Datei speichern
df_small.to_csv("data/test_dashboard_air_quality.csv", index=False)

In [5]:
df_small["City"].unique()

array(['Berlin', 'Hamburg', 'Karlsruhe'], dtype=object)